### ISSUE TITLE
api loading error on prod 3.3.7

### ISSUE THREAD

**Issue by thimios** [alephdata/aleph#873]
I did a fresh prod installation of 3.3.7 and I am getting the following error in the logs:

```
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 340, in import_app
api_1               |     app = getattr(mod, obj)
api_1               | AttributeError: module 'aleph.manage' has no attribute 'app'
api_1               | 
api_1               | During handling of the above exception, another exception occurred:
api_1               | 
api_1               | Traceback (most recent call last):
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
api_1               |     worker.init_process()
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 133, in init_process
api_1               |     self.load_wsgi()
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 142, in load_wsgi
api_1               |     self.wsgi = self.app.wsgi()
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
api_1               |     self.callable = self.load()
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
api_1               |     return self.load_wsgiapp()
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
api_1               |     return util.import_app(self.app_uri)
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 344, in import_app
api_1               |     raise AppImportError("Failed to find application object %r in %r" % (obj, module))
api_1               | gunicorn.errors.AppImportError: Failed to find application object 'app' in 'aleph.manage'
api_1               | Failed to find application object 'app' in 'aleph.manage'
api_1               | [2019-11-21 13:13:46 +0000] [9] [INFO] Worker exiting (pid: 9)
api_1               | Traceback (most recent call last):
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 340, in import_app
api_1               |     app = getattr(mod, obj)
api_1               | AttributeError: module 'aleph.manage' has no attribute 'app'
api_1               | [2019-11-21 13:13:46 +0000] [11] [DEBUG] Exception while loading the application
api_1               | Traceback (most recent call last):
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 340, in import_app
api_1               |     app = getattr(mod, obj)
api_1               | AttributeError: module 'aleph.manage' has no attribute 'app'
api_1               | 
api_1               | During handling of the above exception, another exception occurred:
api_1               | 
api_1               | Traceback (most recent call last):
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
api_1               |     worker.init_process()
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 133, in init_process
api_1               |     self.load_wsgi()
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 142, in load_wsgi
api_1               |     self.wsgi = self.app.wsgi()
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
api_1               |     self.callable = self.load()
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
api_1               |     return self.load_wsgiapp()
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
api_1               |     return util.import_app(self.app_uri)
api_1               |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 344, in import_app
api_1               |     raise AppImportError("Failed to find application object %r in %r" % (obj, module))
api_1               | gunicorn.errors.AppImportError: Failed to find application object 'app' in 'aleph.manage'
api_1               | Failed to find application object 'app' in 'aleph.manage'
api_1               | [2019-11-21 13:13:46 +0000] [11] [INFO] Worker exiting (pid: 11)
```

**Comment by pudo** [comment]
Fixed in 3.3.8, the WSGI app is now: `aleph.wsgi:app`.

**Comment by thimios** [comment]
@pudo I just did `docker system prune --volumes` and rebuilt everything with docker-compose on 3.3.8.:

`docker-compose -f docker-compose.yml up --force-recreate`

I am still getting the same error. Is it possible that I am doing something wrong?

**Comment by pudo** [comment]
Is the error message now listing `aleph.wsgi:app` instead of `aleph.manage:app`? Otherwise is it possible you need to update your compose file based on the changed invocation of `aleph.manage`? See the current `docker-compose.yml`.
